name: Release

on:
  push:
    branches:
      - 7.x
  workflow_dispatch:

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build push filebeat
        uses: docker/build-push-action@v3
        with:
          context: ./filebeat
          file: ./filebeat/Dockerfile
          push: true
          tags: ttbb/filebeat:nake-7
          platforms: linux/amd64,linux/arm64
      - name: build push heartbeat
        uses: docker/build-push-action@v3
        with:
          context: ./heartbeat
          file: ./heartbeat/Dockerfile
          push: true
          tags: ttbb/heartbeat:nake-7
          platforms: linux/amd64,linux/arm64
      - name: build push metricbeat
        uses: docker/build-push-action@v3
        with:
          context: ./metricbeat
          file: ./metricbeat/Dockerfile
          push: true
          tags: ttbb/metricbeat:nake-7
          platforms: linux/amd64,linux/arm64
      - name: build push metricbeat
        uses: docker/build-push-action@v3
        with:
          context: ./packetbeat
          file: ./packetbeat/Dockerfile
          push: true
          tags: ttbb/packetbeat:nake-7
          platforms: linux/amd64,linux/arm64
